### ISSUE TITLE
Issues with the UI

### ISSUE THREAD

**Issue by mustafawm** [skidding/react-testing-examples#28]
Hi,

I see the "last" commit message saying updating `setupTestFrameworkScriptFile ` (deprecated) to `setupFilesAfterEnv` but the UI is still showing the old config

Also, clicking on the Open-in-Github icon (top right corner of snippets) results in 404

**Comment by skidding** [comment]
Fixed: https://react-testing-examples.com/

Thanks @mustafawm! Let me know if you find other issues.
