### ISSUE TITLE
Domain react-testing-examples

### ISSUE THREAD

**Issue by timdeschryver** [skidding/react-testing-examples#56]
Hi, I'm coming from https://github.com/testing-library/testing-library-docs/pull/1059.
Could you help us out and verify the domain for react-testing-examples please?

**Comment by ovidiuch** [comment]
Hi, the domain expired and I decided not to renew it. Too many domains that don't provide any income... :)

Please point the link to https://react-testing-examples.netlify.app

**Comment by timdeschryver** [comment]
Cool, thanks for the fast response 💙!
